stages:
   - documentation
   - quality
   - build
   - unit_test
   - active_tests

variables:
  GIT_STRATEGY: clone
  TIMEOUT: 10m

docs:
   stage: documentation
   script:
      - make docs
   artifacts:
      paths:
         - docs/code/src

styleCheck:
   stage: quality
   script:
      - make style

staticAnalysis:
   stage: quality
   script:
      - make static

buildTests:
   stage: build
   script:
      - make test_blackjack
   artifacts:
      paths:
         - test_blackjack

unitTests:
   stage: unit_test
   script:
      - test_blackjack

memoryLeaks:
   stage: active_tests
   script:
      - make memcheck

coverage:
   stage: active_tests
   script:
      - make coverage
   artifacts:
     paths:
        - coverage
